[[events]]
name = "increment"
event_type = "EV_KEY"
key_state = "released"
keys = ["KEY_VOLUMEDOWN", "KEY_POWER"]
command = "/usr/bin/togglevt.sh inc"

[[events]]
name = "start"
event_type = "EV_KEY"
key_state = "pressed"
keys = ["KEY_VOLUMEDOWN"]
command = "/usr/bin/togglevt.sh start"

[[events]]
name = "reset"
event_type = "EV_KEY"
key_state = "released"
keys = ["KEY_VOLUMEDOWN"]
command = "/usr/bin/togglevt.sh reset"